version: '3.1'
services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: local-openldap
    environment:
      LDAP_ORGANISATION: "ExampleOrg"
      LDAP_DOMAIN: "example.org"
      LDAP_ADMIN_PASSWORD: "admin"
    ports:
      - "389:389"
    volumes:
      - ./ldap-data:/var/lib/ldap
      - ./ldap-config:/etc/ldap/slapd.d
    restart: unless-stopped
